version: "3"
services:
  fashionscape-api:
    build: ./
    command: pm2-dev start src/server.js
    container_name: fashionscape-api
    environment:
      - RS_HOST=localhost:8001
    image: floramoon/fashionscape-api:latest
    ports:
      - "8000:8000"
      - "8001:8000"
    restart: always
    volumes:
      - "./config:/usr/src/app/config"
      - "./data:/usr/src/app/data"
      - "./node_modules:/usr/src/app/node_modules"
      - "./src:/usr/src/app/src"
